import type { Review } from "@/types/review";

export const MOCK_REVIEWS: Review[] = [
  {
    id: "mock-1",
    source: "play_store",
    external_review_id: "ps-001",
    author_name: "Rahul Sharma",
    rating: 1,
    review_text: "App crashes every time I try to download a status. Worst app ever. Please fix this immediately!",
    review_language: "en",
    reply_status: "pending",
    sentiment: "negative",
    keywords: ["crash", "download", "fix"],
    is_read: false,
    review_created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-2",
    source: "play_store",
    external_review_id: "ps-002",
    author_name: "Priya Patel",
    rating: 5,
    review_text: "Amazing app! I love how easy it is to save WhatsApp statuses. The batch download feature is a lifesaver. Keep up the great work!",
    review_language: "en",
    reply_status: "pending",
    sentiment: "positive",
    keywords: ["easy", "save", "batch download"],
    is_read: false,
    review_created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-3",
    source: "google_business",
    external_review_id: "gbp-001",
    author_name: "Amit Kumar",
    rating: 3,
    review_text: "Food was good but the wait time was too long. We waited 45 minutes for our order. The staff was friendly though.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "mixed",
    keywords: ["wait time", "food", "staff", "friendly"],
    is_read: false,
    review_created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-4",
    source: "play_store",
    external_review_id: "ps-003",
    author_name: "Sneha Reddy",
    rating: 2,
    review_text: "Too many ads! I understand you need revenue but an ad after every single download is ridiculous. Would rate 5 stars without ads.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "negative",
    keywords: ["ads", "revenue", "download"],
    is_read: false,
    review_created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-5",
    source: "google_business",
    external_review_id: "gbp-002",
    author_name: "Vikram Singh",
    rating: 5,
    review_text: "Best dentist in the area! Dr. Mehta is very gentle and explains everything clearly. The clinic is very clean and modern. Highly recommended!",
    review_language: "en",
    reply_status: "published",
    reply_text: "Thank you so much, Vikram! Dr. Mehta will be delighted to hear your kind words. We take pride in making every visit comfortable and transparent. Looking forward to seeing you at your next checkup!",
    sentiment: "positive",
    keywords: ["dentist", "gentle", "clean", "modern"],
    is_read: true,
    is_auto_replied: true,
    review_created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-6",
    source: "play_store",
    external_review_id: "ps-004",
    author_name: "Arjun Nair",
    rating: 4,
    review_text: "Good app overall. Works well for saving statuses. Only issue is it sometimes doesn't detect new statuses until I restart the app.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "positive",
    keywords: ["good", "statuses", "restart"],
    is_read: false,
    review_created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-7",
    source: "google_business",
    external_review_id: "gbp-003",
    author_name: "Meera Joshi",
    rating: 1,
    review_text: "Terrible experience. Booked an appointment for 10am, wasn't seen until 11:30am. No apology from anyone. Will not be returning.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "negative",
    keywords: ["appointment", "terrible", "waiting"],
    is_read: false,
    review_created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-8",
    source: "play_store",
    external_review_id: "ps-005",
    author_name: "Deepak Verma",
    rating: 5,
    review_text: "Bahut accha app hai! Sab kuch easily save ho jata hai. Video quality bhi original jaisi rehti hai. 5 star deserve karta hai ye app!",
    review_language: "hi",
    reply_status: "pending",
    sentiment: "positive",
    keywords: ["accha", "easily", "quality"],
    is_read: false,
    review_created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-9",
    source: "google_business",
    external_review_id: "gbp-004",
    author_name: "Kavita Deshmukh",
    rating: 4,
    review_text: "Great food and ambiance. The paneer tikka was excellent! Slightly overpriced but the quality makes up for it. Would visit again.",
    review_language: "en",
    reply_status: "published",
    reply_text: "Thank you, Kavita! We're glad you enjoyed the paneer tikka — it's one of our chef's favorites too! We appreciate your feedback on pricing and strive to deliver the best quality ingredients. Hope to see you again soon!",
    sentiment: "positive",
    keywords: ["food", "ambiance", "paneer tikka", "quality"],
    is_read: true,
    review_created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-10",
    source: "play_store",
    external_review_id: "ps-006",
    author_name: "Suresh Menon",
    rating: 3,
    review_text: "App works but the UI looks outdated. How do I enable dark mode? Also, does this work with WhatsApp Business?",
    review_language: "en",
    reply_status: "pending",
    sentiment: "mixed",
    keywords: ["UI", "dark mode", "WhatsApp Business"],
    is_read: false,
    review_created_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-11",
    source: "google_business",
    external_review_id: "gbp-005",
    author_name: "Ananya Chatterjee",
    rating: 5,
    review_text: "Dr. Shah is the best pediatrician! So patient with my kids and always explains everything in detail. The clinic is child-friendly with toys and books. Highly recommend for new parents!",
    review_language: "en",
    reply_status: "drafted",
    reply_text: "Thank you so much, Ananya! Dr. Shah truly cares about every child's comfort and well-being. We're glad the play area makes visits easier for your little ones. See you at the next appointment!",
    sentiment: "positive",
    keywords: ["pediatrician", "patient", "child-friendly"],
    is_read: true,
    review_created_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-12",
    source: "play_store",
    external_review_id: "ps-007",
    author_name: "Rohit Gupta",
    rating: 1,
    review_text: "App asked for storage permission and then deleted some of my photos! This is a scam app. Uninstalling immediately and reporting to Google.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "negative",
    keywords: ["permission", "deleted", "scam"],
    is_read: false,
    review_created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-13",
    source: "google_business",
    external_review_id: "gbp-006",
    author_name: "Fatima Sheikh",
    rating: 2,
    review_text: "The plumber came 2 hours late and charged more than the quoted price. The actual work was fine but the service experience was poor.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "negative",
    keywords: ["late", "overcharged", "plumber"],
    is_read: false,
    review_created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-14",
    source: "play_store",
    external_review_id: "ps-008",
    author_name: "Kiran Rao",
    rating: 4,
    review_text: "Love the app! Just one suggestion — can you add support for saving Instagram stories too? That would make this the perfect all-in-one saver.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "positive",
    keywords: ["love", "Instagram", "suggestion"],
    is_read: false,
    review_created_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-15",
    source: "google_business",
    external_review_id: "gbp-007",
    author_name: "Rajesh Pillai",
    rating: 5,
    review_text: "Excellent salon! Got a haircut and beard trim. Ravi is very skilled and takes his time to get it right. Clean, modern, and great music. Best grooming experience in Bangalore.",
    review_language: "en",
    reply_status: "published",
    reply_text: "Thank you, Rajesh! Ravi will be thrilled to hear this. We believe every visit should feel special. Looking forward to your next grooming session!",
    sentiment: "positive",
    keywords: ["salon", "skilled", "clean", "modern"],
    is_read: true,
    is_auto_replied: true,
    review_created_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-16",
    source: "play_store",
    external_review_id: "ps-009",
    author_name: "Neha Agarwal",
    rating: 2,
    review_text: "Was working fine until the last update. Now keeps showing 'storage full' error even though I have 20GB free. Please fix this bug!",
    review_language: "en",
    reply_status: "pending",
    sentiment: "negative",
    keywords: ["update", "storage", "bug", "error"],
    is_read: false,
    review_created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-17",
    source: "google_business",
    external_review_id: "gbp-008",
    author_name: "Sanjay Malhotra",
    rating: 3,
    review_text: "Decent gym with good equipment. But it gets very crowded after 6pm and half the machines are occupied. Need more space or limit memberships.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "mixed",
    keywords: ["gym", "crowded", "equipment", "memberships"],
    is_read: false,
    review_created_at: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-18",
    source: "play_store",
    external_review_id: "ps-010",
    author_name: "Pooja Iyer",
    rating: 5,
    review_text: "Simple and effective! No unnecessary features, just does what it says. Downloaded over 500 statuses without any issues. Thank you developers!",
    review_language: "en",
    reply_status: "pending",
    sentiment: "positive",
    keywords: ["simple", "effective", "no issues"],
    is_read: false,
    review_created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-19",
    source: "google_business",
    external_review_id: "gbp-009",
    author_name: "Vivek Saxena",
    rating: 4,
    review_text: "Good tutoring center. My son's math scores improved from 60% to 85% in 3 months. Only drawback is parking is difficult in the area.",
    review_language: "en",
    reply_status: "pending",
    sentiment: "positive",
    keywords: ["tutoring", "math", "improved", "parking"],
    is_read: false,
    review_created_at: new Date(Date.now() - 80 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-20",
    source: "play_store",
    external_review_id: "ps-011",
    author_name: "Aditya Bhatt",
    rating: 1,
    review_text: "Ye app kaam nahi karta. Install karte hi crash ho raha hai. Samsung Galaxy M31 pe test karo please. 1 star bhi zyada hai iske liye.",
    review_language: "hi",
    reply_status: "pending",
    sentiment: "negative",
    keywords: ["crash", "kaam nahi", "Samsung"],
    is_read: false,
    review_created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_AUTO_REPLY_STATS = {
  total_this_month: 47,
  published_automatically: 42,
  drafted_for_review: 5,
  last_run: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  next_run_time: "08:00 AM",
};

export const MOCK_ANALYTICS = {
  total_reviews: 247,
  avg_rating: 4.1,
  response_rate: 78,
  avg_response_time_hours: 2.3,
  rating_trend: [
    { date: "2026-03-01", avg_rating: 3.8, count: 12 },
    { date: "2026-03-08", avg_rating: 3.9, count: 15 },
    { date: "2026-03-15", avg_rating: 4.0, count: 18 },
    { date: "2026-03-22", avg_rating: 4.2, count: 14 },
    { date: "2026-03-29", avg_rating: 4.1, count: 11 },
  ],
  sentiment_breakdown: { positive: 58, negative: 22, neutral: 12, mixed: 8 },
  top_keywords: [
    { word: "great service", count: 34 },
    { word: "slow", count: 18 },
    { word: "friendly staff", count: 28 },
    { word: "too expensive", count: 12 },
    { word: "recommend", count: 31 },
    { word: "wait time", count: 15 },
    { word: "easy to use", count: 22 },
    { word: "crash", count: 9 },
  ],
};
