"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * "This week at a glance" — renders the LATEST persisted AI executive summary
 * generated by the weekly digest. Read-only: the card fetches one row from
 * /api/dashboard/exec-summary, which only reads the executive_summaries
 * table. It never triggers AI generation.
 *
 * Hidden entirely when DIGEST_EXECUTIVE_SUMMARY_ENABLED is off (the API
 * reports enabled:false).
 */

interface ExecSummaryResponse {
  enabled: boolean;
  weeklyDigestEnabled?: boolean;
  summary: {
    summary: string;
    topAction: string;
    periodStart: string;
    periodEnd: string;
    createdAt: string;
  } | null;
}

const STALE_AFTER_MS = 14 * 86400000;

function fmtDate(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-IN", { month: "short", day: "numeric" });
}

export function WeeklyGlanceCard({ className }: { className?: string }) {
  const [data, setData] = useState<ExecSummaryResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const res = await fetch("/api/dashboard/exec-summary", {
          cache: "no-store",
        });
        if (!res.ok) {
          if (!cancelled) setData(null);
          return;
        }
        const d = (await res.json()) as ExecSummaryResponse;
        if (!cancelled) setData(d);
      } catch {
        if (!cancelled) setData(null);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, []);

  // Feature flag off (or fetch failed) → no card at all, no broken placeholder.
  if (!loading && (!data || !data.enabled)) return null;

  const summary = data?.summary ?? null;
  const isStale =
    summary != null &&
    Date.now() - new Date(summary.createdAt).getTime() > STALE_AFTER_MS;

  return (
    <Card
      className={cn(
        "group relative overflow-hidden transition-all duration-200",
        "hover:-translate-y-px hover:border-accent/30 hover:shadow-[0_4px_24px_-12px_hsl(var(--ring)/0.25)]",
        className
      )}
    >
      <CardContent className="p-5">
        <div className="flex items-center justify-between mb-3 gap-2">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider min-w-0 truncate">
            This Week at a Glance
          </p>
          <div className="rounded-lg p-2 ring-1 ring-inset ring-border/40 bg-violet-50 text-violet-500 dark:bg-violet-950/30 shrink-0">
            <Sparkles className="h-4 w-4" aria-hidden />
          </div>
        </div>

        {loading ? (
          <div className="space-y-2" aria-label="Loading summary…">
            <div className="h-3.5 w-full rounded bg-muted/50 animate-pulse" />
            <div className="h-3.5 w-5/6 rounded bg-muted/40 animate-pulse" />
            <div className="h-3.5 w-2/3 rounded bg-muted/40 animate-pulse" />
          </div>
        ) : summary ? (
          <>
            <p className="text-sm leading-relaxed">{summary.summary}</p>
            <div className="mt-3 flex items-start gap-2 rounded-lg bg-accent/10 px-3 py-2.5 ring-1 ring-inset ring-accent/20">
              <ArrowRight className="h-3.5 w-3.5 mt-0.5 text-accent shrink-0" aria-hidden />
              <p className="text-xs font-medium leading-snug">{summary.topAction}</p>
            </div>
            <div className="mt-3 flex items-center justify-between flex-wrap gap-1 text-[10px] text-muted-foreground/80 font-mono">
              <span>
                {fmtDate(summary.periodStart)} – {fmtDate(summary.periodEnd)}
              </span>
              {isStale && (
                <span className="text-muted-foreground/60">
                  from {fmtDate(summary.createdAt)}
                </span>
              )}
            </div>
          </>
        ) : (
          <div className="py-1">
            <p className="text-sm text-muted-foreground leading-relaxed">
              Your first AI summary arrives with your weekly digest.
            </p>
            {data?.weeklyDigestEnabled === false && (
              <p className="text-xs text-muted-foreground/80 mt-2">
                Weekly digest is off —{" "}
                <Link
                  href="/dashboard/settings/notifications"
                  className="underline underline-offset-2 text-foreground/80 hover:text-foreground"
                >
                  enable it in Settings → Notifications
                </Link>
              </p>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
