-- 044_executive_summaries.sql
-- Persist the weekly AI executive summary so the dashboard "This week at a
-- glance" card can REUSE the digest-generated summary instead of making any
-- AI call of its own.
--
-- Additive only — new table, no existing object touched.
--
-- Write path: service role only (the weekly digest send pipeline upserts).
-- Read path: owner + team members via the same get_effective_owner_id
-- pattern as alert_preferences (migration 043).

create table if not exists public.executive_summaries (
  id uuid primary key default gen_random_uuid(),
  -- Always the WORKSPACE OWNER's id (the digest runs per owner).
  user_id uuid not null references public.profiles(id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  -- Matches the generator's output shape ({ summary, topAction }).
  summary text not null,
  top_action text not null,
  model text,
  created_at timestamptz not null default now(),
  -- One summary per weekly slot per user. The digest upserts on this key so
  -- cron retries for the same week never create duplicate rows.
  unique (user_id, period_start)
);

alter table public.executive_summaries enable row level security;

drop policy if exists "Team can read executive summaries" on public.executive_summaries;
create policy "Team can read executive summaries" on public.executive_summaries
  for select using (user_id = public.get_effective_owner_id(auth.uid()));

-- No INSERT/UPDATE/DELETE policies — writes go through the service role only.

create index if not exists idx_executive_summaries_user_created
  on public.executive_summaries(user_id, created_at desc);

comment on table public.executive_summaries is
  'Weekly AI executive summaries generated by the digest pipeline. The dashboard card reads the latest row — it never triggers generation.';
